#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: tools/runtime-validation/start-local.sh [--empty] [--foreground]

Starts the Akka-hosted local runtime-validation app on http://localhost:9000.
The script loads .env when present, enables the local-only runtime-validation
seed endpoint, writes the seed token to .runtime-validation/local.env, and
builds the frontend assets, then runs `mvn clean compile exec:java -Dakka.runtime.http-interface=0.0.0.0` unless --foreground is omitted, in which case the
backend starts in the background and logs to .runtime-validation/logs/backend.log.
It waits for the HTTP endpoint to become reachable before returning. Stop a
script-started background backend with `tools/runtime-validation/stop-local.sh`.

Options:
  --empty       stop any prior script-started backend and start a fresh dev run
  --foreground  run Maven in the foreground
USAGE
}

EMPTY=false
FOREGROUND=false
for arg in "$@"; do
  case "$arg" in
    --empty) EMPTY=true ;;
    --foreground) FOREGROUND=true ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $arg" >&2; usage >&2; exit 2 ;;
  esac
done

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

STATE_DIR=".runtime-validation"
LOG_DIR="$STATE_DIR/logs"
LOCAL_ENV="$STATE_DIR/local.env"
PID_FILE="$STATE_DIR/backend.pid"
mkdir -p "$LOG_DIR"
chmod 700 "$STATE_DIR"

load_env_defaults() {
  local file="$1"
  [[ -f "$file" ]] || return 0
  local line key value
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^[[:space:]]*# || ! "$line" =~ ^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*= ]] && continue
    line="${line#${line%%[![:space:]]*}}"
    key="${line%%=*}"
    value="${line#*=}"
    value="${value#${value%%[![:space:]]*}}"
    value="${value%${value##*[![:space:]]}}"
    if [[ ( "${value:0:1}" == '"' && "${value: -1}" == '"' ) || ( "${value:0:1}" == "'" && "${value: -1}" == "'" ) ]]; then
      value="${value:1:${#value}-2}"
    fi
    if [[ -z "${!key+x}" ]]; then
      export "${key}=${value}"
    fi
  done < "$file"
}

load_env_defaults ".env"

if [[ ! -f "$LOCAL_ENV" ]]; then
  token="$(python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(32))
PY
)"
  cat > "$LOCAL_ENV" <<EOF
# Generated by tools/runtime-validation/start-local.sh.
# Keep this file local; it authorizes only local runtime-validation seeding.
RUNTIME_VALIDATION_SEED_TOKEN='$token'
RUNTIME_VALIDATION_BASE_URL='http://localhost:9000'
EOF
  chmod 600 "$LOCAL_ENV"
fi
load_env_defaults "$LOCAL_ENV"

export APP_ENV="${APP_ENV:-local}"
export APP_PUBLIC_BASE_URL="${APP_PUBLIC_BASE_URL:-http://localhost:9000/}"
export RUNTIME_VALIDATION_SEED_ENABLED="true"
export RUNTIME_VALIDATION_SEED_TOKEN="${RUNTIME_VALIDATION_SEED_TOKEN:?missing generated seed token}"

if [[ "$EMPTY" == true && -f "$PID_FILE" ]]; then
  ./tools/runtime-validation/stop-local.sh --force
fi

missing=()
for key in WORKOS_JWT_ISSUER WORKOS_JWT_AUDIENCE VITE_WORKOS_CLIENT_ID VITE_WORKOS_REDIRECT_URI; do
  value="${!key:-}"
  if [[ -z "$value" || "$value" =~ your_|configured-workos|client_your|replace_with|xxxxxxxx ]]; then
    missing+=("$key")
  fi
done
if (( ${#missing[@]} > 0 )); then
  printf 'Runtime-validation auth config is missing or placeholder: %s\n' "${missing[*]}" >&2
  printf 'Set real local WorkOS/AuthKit values in the process environment or .env before running RV-MY-ACCOUNT-001.\n' >&2
  exit 78
fi

echo "Building frontend assets."
npm --prefix frontend run build

COMMAND=(mvn clean compile exec:java -Dakka.runtime.http-interface=0.0.0.0)
if [[ "$FOREGROUND" == true ]]; then
  echo "Starting Akka runtime in foreground: ${COMMAND[*]}"
  echo "Frontend/API URL: http://localhost:9000"
  exec "${COMMAND[@]}"
fi

if [[ -f "$PID_FILE" ]]; then
  current_pid="$(cat "$PID_FILE" || true)"
  if [[ -n "$current_pid" ]] && kill -0 "$current_pid" 2>/dev/null; then
    echo "Runtime-validation backend already running with pid $current_pid; waiting for readiness"
    for _ in {1..90}; do
      if curl -fsS "http://localhost:9000/" >/dev/null 2>&1; then
        echo "Frontend/API URL: http://localhost:9000"
        echo "Seed env: $LOCAL_ENV"
        exit 0
      fi
      if ! kill -0 "$current_pid" 2>/dev/null; then
        echo "Existing runtime-validation backend exited before becoming ready. Remove $PID_FILE or restart with --empty." >&2
        exit 1
      fi
      sleep 2
    done
    echo "Existing runtime-validation backend did not become ready at http://localhost:9000 within 180 seconds. Use tools/runtime-validation/stop-local.sh --force or restart with --empty." >&2
    exit 1
  fi
  rm -f "$PID_FILE"
fi

log_file="$LOG_DIR/backend.log"
echo "Starting Akka runtime in background: ${COMMAND[*]}"
("${COMMAND[@]}") >"$log_file" 2>&1 &
pid=$!
echo "$pid" > "$PID_FILE"

for _ in {1..90}; do
  if curl -fsS "http://localhost:9000/" >/dev/null 2>&1; then
    echo "Runtime-validation backend pid: $pid"
    echo "Frontend/API URL: http://localhost:9000"
    echo "Seed env: $LOCAL_ENV"
    echo "Log: $log_file"
    exit 0
  fi
  if ! kill -0 "$pid" 2>/dev/null; then
    echo "Akka runtime exited before becoming ready. See $log_file" >&2
    exit 1
  fi
  sleep 2
done

echo "Akka runtime did not become ready at http://localhost:9000 within 180 seconds. See $log_file" >&2
exit 1
