package {{JAVA_BASE_PACKAGE}}.domain.security;

import java.util.List;

/** Canonical foundation roles; app roles extend these instead of replacing them. */
public enum FoundationRole {
  SAAS_OWNER_ADMIN(
      ScopeType.SAAS_OWNER,
      List.of(
          "profile.read",
          "profile.update",
          "my_account.view_summary",
          "my_account.view_context",
          "my_account.update_profile_settings",
          "my_account.list_next_steps",
          "my_account.open_authorized_workstream",
          "my_account.ask_agent",
          "my_account.view_own_trace_refs",
          "saas_owner.user.manage",
          "saas_owner.tenant.read",
          "saas_owner.tenant.manage",
          "saas_owner.audit.read",
          "saas_owner.billing_boundary.manage")),
  TENANT_ADMIN(
      ScopeType.TENANT,
      List.of(
          "profile.read",
          "profile.update",
          "my_account.view_summary",
          "my_account.view_context",
          "my_account.update_profile_settings",
          "my_account.list_next_steps",
          "my_account.open_authorized_workstream",
          "my_account.ask_agent",
          "my_account.view_own_trace_refs",
          "secure-tenant-user-foundation",
          "tenant.user.read",
          "tenant.user.manage",
          "tenant.role.manage",
          "tenant.invitation.manage",
          "tenant.customer.manage",
          "tenant.support_access.manage",
          "tenant.audit.read",
          "tenant.access_review.manage",
          "audit.trace.read",
          "governance.policy.read",
          "governance.policy.simulate",
          "governance.policy.commit",
          "improvements.create",
          "improvements.review",
          "improvements.activate",
          "agent.user_admin.use",
          "agent.behavior.manage",
          "agent.definitions.manage",
          "agent.prompts.govern",
          "agent.skills.govern",
          "agent.tool_boundaries.manage",
          "agent.models.read",
          "agent.models.manage",
          "agent.runtime.test",
          "agent_admin.submit_turn",
          "agent_admin.list_definitions",
          "agent_admin.get_definition",
          "agent_admin.get_prompt_version",
          "agent_admin.get_skill_version",
          "agent_admin.get_reference_version",
          "agent_admin.get_manifest",
          "agent_admin.get_model_ref",
          "agent_admin.get_tool_boundary",
          "agent_admin.simulate_tool_boundary",
          "agent_admin.draft_behavior_change",
          "agent_admin.submit_behavior_change_for_review",
          "agent_admin.approve_behavior_change",
          "agent_admin.reject_behavior_change",
          "agent_admin.activate_behavior_change",
          "agent_admin.cancel_behavior_change",
          "agent_admin.list_seed_material",
          "agent_admin.reseed_missing_defaults",
          "agent_admin.start_behavior_review_task",
          "agent_admin.get_behavior_review_task",
          "agent_admin.cancel_behavior_review_task")),
  TENANT_EMPLOYEE(
      ScopeType.TENANT,
      List.of(
          "profile.read",
          "profile.update",
          "my_account.view_summary",
          "my_account.view_context",
          "my_account.update_profile_settings",
          "my_account.list_next_steps",
          "my_account.open_authorized_workstream",
          "my_account.ask_agent",
          "my_account.view_own_trace_refs",
          "tenant.app.use",
          "agent.workstream.use")),
  CUSTOMER_ADMIN(
      ScopeType.CUSTOMER,
      List.of(
          "profile.read",
          "profile.update",
          "my_account.view_summary",
          "my_account.view_context",
          "my_account.update_profile_settings",
          "my_account.list_next_steps",
          "my_account.open_authorized_workstream",
          "my_account.ask_agent",
          "my_account.view_own_trace_refs",
          "secure-tenant-user-foundation",
          "customer.user.read",
          "customer.user.manage",
          "customer.role.manage",
          "customer.invitation.manage",
          "customer.audit.read",
          "customer.access_review.manage",
          "audit.trace.read",
          "governance.policy.read",
          "governance.policy.simulate",
          "governance.policy.commit",
          "improvements.create",
          "improvements.review",
          "improvements.activate",
          "agent.user_admin.use",
          "agent.behavior.manage",
          "agent.definitions.manage",
          "agent.prompts.govern",
          "agent.skills.govern",
          "agent.tool_boundaries.manage",
          "agent.models.read",
          "agent.models.manage",
          "agent.runtime.test",
          "agent_admin.submit_turn",
          "agent_admin.list_definitions",
          "agent_admin.get_definition",
          "agent_admin.get_prompt_version",
          "agent_admin.get_skill_version",
          "agent_admin.get_reference_version",
          "agent_admin.get_manifest",
          "agent_admin.get_model_ref",
          "agent_admin.get_tool_boundary",
          "agent_admin.simulate_tool_boundary",
          "agent_admin.draft_behavior_change",
          "agent_admin.submit_behavior_change_for_review",
          "agent_admin.approve_behavior_change",
          "agent_admin.reject_behavior_change",
          "agent_admin.activate_behavior_change",
          "agent_admin.cancel_behavior_change",
          "agent_admin.list_seed_material",
          "agent_admin.reseed_missing_defaults",
          "agent_admin.start_behavior_review_task",
          "agent_admin.get_behavior_review_task",
          "agent_admin.cancel_behavior_review_task")),
  CUSTOMER_USER(
      ScopeType.CUSTOMER,
      List.of(
          "profile.read",
          "profile.update",
          "my_account.view_summary",
          "my_account.view_context",
          "my_account.update_profile_settings",
          "my_account.list_next_steps",
          "my_account.open_authorized_workstream",
          "my_account.ask_agent",
          "my_account.view_own_trace_refs",
          "customer.app.use",
          "agent.workstream.use")),
  AUDITOR(
      ScopeType.TENANT,
      List.of(
          "profile.read",
          "profile.update",
          "my_account.view_summary",
          "my_account.view_context",
          "my_account.list_next_steps",
          "my_account.ask_agent",
          "my_account.view_own_trace_refs",
          "tenant.audit.read",
          "tenant.access_review.read",
          "customer.audit.read",
          "customer.access_review.read"));

  private final ScopeType defaultScopeType;
  private final List<String> capabilities;

  FoundationRole(ScopeType defaultScopeType, List<String> capabilities) {
    this.defaultScopeType = defaultScopeType;
    this.capabilities = List.copyOf(capabilities);
  }

  public ScopeType defaultScopeType() {
    return defaultScopeType;
  }

  public List<String> capabilities() {
    return capabilities;
  }
}
