#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"

fail() {
  printf '[verify-opinionated-ai-first-saas][error] %s\n' "$*" >&2
  exit 1
}

log() {
  printf '[verify-opinionated-ai-first-saas] %s\n' "$*"
}

require_file() {
  local path="$1"
  [[ -f "$REPO_ROOT/$path" ]] || fail "Required file missing: $path"
}

require_rg() {
  local pattern="$1"
  shift
  rg -q -- "$pattern" "$@" || fail "Missing required pattern '$pattern' in: $*"
}

forbid_rg() {
  local pattern="$1"
  shift
  if rg -n -- "$pattern" "$@"; then
    fail "Forbidden pattern '$pattern' found in: $*"
  fi
}

cd "$REPO_ROOT"

log "checking core foundation skill and manifest routing"
require_file "skills/core-saas-foundation/SKILL.md"
require_rg "id: core-saas-foundation" pack/manifest.yaml
require_rg "path: skills/core-saas-foundation" pack/manifest.yaml
require_rg "- core-saas-foundation" pack/manifest.yaml

log "checking mandatory invitation and AI-admin skills and manifest routing"
require_file "skills/akka-saas-invitation-onboarding/SKILL.md"
require_file "skills/ai-first-saas-admin-agents/SKILL.md"
require_rg "id: akka-saas-invitation-onboarding" pack/manifest.yaml
require_rg "path: skills/akka-saas-invitation-onboarding" pack/manifest.yaml
require_rg "- akka-saas-invitation-onboarding" pack/manifest.yaml
require_rg "id: ai-first-saas-admin-agents" pack/manifest.yaml
require_rg "path: skills/ai-first-saas-admin-agents" pack/manifest.yaml
require_rg "- ai-first-saas-admin-agents" pack/manifest.yaml

log "checking mandatory-security doctrine in top-level guidance"
require_rg "Security is mandatory" AGENTS.md pack/AGENTS.md docs/ai-first-saas-application-architecture.md
require_rg "mandatory secure SaaS foundation" AGENTS.md pack/AGENTS.md skills/README.md docs/ai-first-saas-application-architecture.md
require_rg "Applications generated by this skills pack are \*\*secure AI-first SaaS applications by default\*\*" docs/ai-first-saas-application-architecture.md
require_rg "core-saas-foundation" skills/README.md

log "checking broad intake and generation skills route through core foundation"
require_rg "core-saas-foundation" \
  skills/ai-first-saas/SKILL.md \
  skills/akka-solution-decomposition/SKILL.md \
  skills/akka-prd-to-specs-backlog/SKILL.md \
  skills/app-description-bootstrap/SKILL.md \
  skills/app-generate-app/SKILL.md

log "checking invitation onboarding doctrine guardrails"
require_rg "resend" docs/core-ai-first-saas-foundation.md docs/core-saas-identity-tenancy-admin.md docs/security-workos-auth-and-admin.md skills/core-saas-foundation/SKILL.md skills/akka-basic-user-admin/SKILL.md
require_rg "revoke|revoked" docs/core-ai-first-saas-foundation.md docs/core-saas-identity-tenancy-admin.md docs/security-workos-auth-and-admin.md skills/core-saas-foundation/SKILL.md skills/akka-basic-user-admin/SKILL.md
require_rg "expiry|expire|expired" docs/core-ai-first-saas-foundation.md docs/core-saas-identity-tenancy-admin.md docs/security-workos-auth-and-admin.md skills/core-saas-foundation/SKILL.md skills/akka-basic-user-admin/SKILL.md
require_rg "delivery status" docs/core-ai-first-saas-foundation.md docs/core-saas-identity-tenancy-admin.md docs/security-workos-auth-and-admin.md skills/core-saas-foundation/SKILL.md skills/akka-basic-user-admin/SKILL.md
require_rg "InvitationWorkflow" skills/akka-saas-invitation-onboarding/SKILL.md skills/akka-basic-user-admin/SKILL.md docs/core-saas-identity-tenancy-admin.md
require_rg "email delivery/outbox" skills/akka-saas-invitation-onboarding/SKILL.md skills/core-saas-foundation/SKILL.md skills/akka-basic-user-admin/SKILL.md

log "checking admin management and AI-admin doctrine guardrails"
require_rg "UserDirectoryView" docs/core-saas-identity-tenancy-admin.md docs/security-workos-auth-and-admin.md skills/core-saas-foundation/SKILL.md skills/akka-basic-user-admin/SKILL.md
require_rg "MembershipView" docs/core-saas-identity-tenancy-admin.md docs/security-workos-auth-and-admin.md skills/core-saas-foundation/SKILL.md skills/akka-basic-user-admin/SKILL.md
require_rg "InvitationView" docs/core-saas-identity-tenancy-admin.md docs/security-workos-auth-and-admin.md skills/core-saas-foundation/SKILL.md skills/akka-basic-user-admin/SKILL.md
require_rg "AdminAuditView" docs/core-saas-identity-tenancy-admin.md docs/security-workos-auth-and-admin.md skills/core-saas-foundation/SKILL.md skills/akka-basic-user-admin/SKILL.md
require_rg "AccessReviewQueueView" docs/core-saas-identity-tenancy-admin.md docs/security-workos-auth-and-admin.md skills/core-saas-foundation/SKILL.md skills/akka-basic-user-admin/SKILL.md
require_rg "user directory/search|list/search users|search/filter users" docs/core-saas-identity-tenancy-admin.md docs/security-workos-auth-and-admin.md skills/akka-basic-user-admin/SKILL.md
require_rg "membership lifecycle" docs/core-saas-identity-tenancy-admin.md docs/security-workos-auth-and-admin.md skills/core-saas-foundation/SKILL.md skills/akka-basic-user-admin/SKILL.md
require_rg "admin audit/search" docs/core-saas-identity-tenancy-admin.md docs/security-workos-auth-and-admin.md skills/core-saas-foundation/SKILL.md skills/akka-basic-user-admin/SKILL.md
require_rg "access review|Access Review" docs/core-saas-identity-tenancy-admin.md docs/security-workos-auth-and-admin.md skills/core-saas-foundation/SKILL.md skills/akka-basic-user-admin/SKILL.md
require_rg "last-admin" docs/core-saas-identity-tenancy-admin.md docs/security-workos-auth-and-admin.md skills/core-saas-foundation/SKILL.md skills/akka-basic-user-admin/SKILL.md
require_rg "AccessReviewAgent" skills/ai-first-saas-admin-agents/SKILL.md docs/core-saas-identity-tenancy-admin.md skills/core-saas-foundation/SKILL.md
require_rg "AdminRiskAgent" skills/ai-first-saas-admin-agents/SKILL.md docs/core-saas-identity-tenancy-admin.md skills/core-saas-foundation/SKILL.md
require_rg "RoleRecommendationAgent" skills/ai-first-saas-admin-agents/SKILL.md docs/core-saas-identity-tenancy-admin.md skills/core-saas-foundation/SKILL.md
require_rg "AdminAuditSummaryAgent" skills/ai-first-saas-admin-agents/SKILL.md docs/core-saas-identity-tenancy-admin.md skills/core-saas-foundation/SKILL.md

log "checking planning guardrails for full foundation task breakdown"
require_rg "invitation lifecycle" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "email delivery" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "UserDirectoryView" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "MembershipView" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "InvitationView" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "AdminAuditView" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "AccessReviewQueueView" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "AI admin|admin AI" skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "AdminRiskAgent" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "AccessReviewAgent" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "decision cards for risky admin" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md

log "checking governed runtime agent foundation doctrine guardrails"
require_rg "AgentDefinition" README.md skills/README.md docs/core-ai-first-saas-foundation.md skills/core-saas-foundation/SKILL.md skills/akka-agent-behavior-profiles/SKILL.md
require_rg "PromptDocument" README.md skills/README.md docs/core-ai-first-saas-foundation.md skills/core-saas-foundation/SKILL.md skills/akka-agent-prompt-governance/SKILL.md
require_rg "SkillDocument" README.md skills/README.md docs/core-ai-first-saas-foundation.md skills/core-saas-foundation/SKILL.md skills/akka-agent-skill-governance/SKILL.md
require_rg "AgentSkillManifest" README.md skills/README.md docs/core-ai-first-saas-foundation.md skills/core-saas-foundation/SKILL.md skills/akka-agent-skill-governance/SKILL.md
require_rg "ToolPermissionBoundary" README.md skills/README.md docs/core-ai-first-saas-foundation.md skills/core-saas-foundation/SKILL.md skills/akka-agent-behavior-profiles/SKILL.md skills/akka-agent-skill-governance/SKILL.md
require_rg "readSkill\(skillId\)" README.md skills/README.md docs/core-ai-first-saas-foundation.md skills/core-saas-foundation/SKILL.md skills/akka-agent-skill-governance/SKILL.md
require_rg "PromptAssemblyTrace" README.md skills/README.md docs/core-ai-first-saas-foundation.md skills/core-saas-foundation/SKILL.md skills/akka-agent-prompt-governance/SKILL.md
require_rg "SkillLoadTrace" README.md skills/README.md docs/core-ai-first-saas-foundation.md skills/core-saas-foundation/SKILL.md skills/akka-agent-skill-governance/SKILL.md
require_rg "AgentWorkTrace" README.md skills/README.md docs/core-ai-first-saas-foundation.md skills/core-saas-foundation/SKILL.md
require_rg "AgentBehaviorEditorAgent|behavior editing agent|editing-agent" docs/ai-first-saas-application-architecture.md skills/akka-agent-governed-documents/SKILL.md skills/akka-agent-prompt-governance/SKILL.md skills/akka-agent-skill-governance/SKILL.md
require_rg 'prompt maintenance through an `AgentBehaviorEditorAgent`|skill, manifest, and tool-boundary changes through an `AgentBehaviorEditorAgent`|editing-agent proposal' skills/akka-agent-prompt-governance/SKILL.md skills/akka-agent-skill-governance/SKILL.md
require_rg "Prompt and skill content is behavior guidance only|cannot grant tool permissions|does not grant tool permissions" skills/core-saas-foundation/SKILL.md skills/akka-agent-skill-governance/SKILL.md docs/ai-first-saas-application-architecture.md

log "checking governed runtime agent foundation planning and task-generation guardrails"
require_rg "AgentDefinition" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "PromptDocument" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "SkillDocument" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "AgentSkillManifest" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "readSkill" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "PromptAssemblyTrace" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "SkillLoadTrace" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "behavior editing|AgentBehaviorEditorAgent" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "too broad|split" skills/akka-backlog-to-pending-tasks/SKILL.md skills/akka-slice-spec-to-backlog/SKILL.md skills/akka-backlog-item-to-task-brief/SKILL.md docs/pending-task-queue.md
require_rg "agent catalog" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md
require_rg "agent detail" skills/akka-solution-decomposition/SKILL.md skills/akka-prd-to-specs-backlog/SKILL.md docs/module-sprint-planning.md docs/pending-task-queue.md

log "checking governed runtime agent foundation core app-description assets"
require_rg "AgentDefinition" app-description
require_rg "PromptDocument" app-description
require_rg "SkillDocument" app-description
require_rg "AgentSkillManifest" app-description
require_rg "ToolPermissionBoundary|tool permission" app-description
require_rg "readSkill" app-description
require_rg "PromptAssemblyTrace" app-description
require_rg "SkillLoadTrace" app-description
require_rg "AgentWorkTrace" app-description
require_rg "AgentBehaviorEditorAgent|editing-agent" app-description
require_rg "agent catalog" app-description
require_rg "agent detail" app-description
require_rg "unauthorized.*PromptDocument|unassigned skill denial|disabled-agent denial|authority expansion" app-description

log "checking packaged docs and core app-description assets"
require_rg "docs/core-ai-first-saas-foundation.md" pack/manifest.yaml tools/build-pack.sh install.sh
require_rg "docs/core-saas-identity-tenancy-admin.md" pack/manifest.yaml tools/build-pack.sh install.sh
require_rg "docs/core-saas-owner-tenant-billing.md" pack/manifest.yaml tools/build-pack.sh install.sh
require_rg "app-description/README.md" pack/manifest.yaml
require_rg "app-description/00-system/app-manifest.md" pack/manifest.yaml
require_rg "docs/workstream-ui-reference-architecture.md" pack/manifest.yaml tools/build-pack.sh
require_rg "docs/agent-workstream-design-review-checklist.md" pack/manifest.yaml tools/build-pack.sh
require_rg "docs/examples/README.md" pack/manifest.yaml tools/build-pack.sh
require_rg "docs/frontend-with-akka-backend.md" pack/manifest.yaml tools/build-pack.sh skills/akka-web-ui-apps/SKILL.md skills/akka-web-ui-frontend-project/SKILL.md skills/akka-workos-user-auth/SKILL.md
require_rg "resources/examples/frontend" pack/AGENTS.md pack/README.md pack/manifest.yaml install.sh
require_rg "copy_frontend_reference" tools/build-pack.sh install.sh
require_rg "\.env\.example" tools/build-pack.sh install.sh
require_rg "frontend/src/workstream" docs/workstream-ui-reference-architecture.md frontend/README.md skills/akka-web-ui-apps/SKILL.md
require_rg "resources/examples/frontend" frontend/README.md install.sh

log "checking forbidden optional-security phrasing in top-level routing files"
forbid_rg "security.*optional|optional.*security|when security is in scope|only when security is in scope|JWT/internal security skills only when security is in scope|generic Akka app|ordinary Akka app|CRUD-first" \
  AGENTS.md \
  pack/AGENTS.md \
  skills/README.md \
  docs/ai-first-saas-application-architecture.md

log "checking generic domain terminology guardrails"
require_rg "DCA-specific.*unless DCA is explicitly the user.s domain|historical/example domain names as generic placeholders" \
  AGENTS.md \
  pack/AGENTS.md \
  skills/README.md

log "checking forbidden optional invitation-email phrasing in foundation/admin docs"
forbid_rg "optional invite email|optionally sends invite|optionally send invite|invite email delivery is optional|invite email.*may be omitted|email-invite.*optional|optional.*email-invite" \
  docs/core-ai-first-saas-foundation.md \
  docs/core-saas-identity-tenancy-admin.md \
  docs/security-workos-auth-and-admin.md \
  skills/core-saas-foundation/SKILL.md \
  skills/akka-basic-user-admin/SKILL.md \
  skills/akka-workos-user-auth/SKILL.md \
  skills/akka-saas-invitation-onboarding/SKILL.md

log "checking shell syntax for pack scripts"
bash -n tools/build-pack.sh install.sh

log "verification passed"
