#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"

fail() {
  printf '[verify-opinionated-ai-first-saas][error] %s\n' "$*" >&2
  exit 1
}

log() {
  printf '[verify-opinionated-ai-first-saas] %s\n' "$*"
}

require_file() {
  local path="$1"
  [[ -f "$REPO_ROOT/$path" ]] || fail "Required file missing: $path"
}

require_rg() {
  local pattern="$1"
  shift
  rg -q -- "$pattern" "$@" || fail "Missing required pattern '$pattern' in: $*"
}

forbid_rg() {
  local pattern="$1"
  shift
  if rg -n -- "$pattern" "$@"; then
    fail "Forbidden pattern '$pattern' found in: $*"
  fi
}

cd "$REPO_ROOT"

log "checking core foundation skill and manifest routing"
require_file "skills/core-saas-foundation/SKILL.md"
require_rg "id: core-saas-foundation" pack/manifest.yaml
require_rg "path: skills/core-saas-foundation" pack/manifest.yaml
require_rg "- core-saas-foundation" pack/manifest.yaml

log "checking mandatory-security doctrine in top-level guidance"
require_rg "Security is mandatory" AGENTS.md pack/AGENTS.md docs/ai-first-saas-application-architecture.md
require_rg "mandatory secure SaaS foundation" AGENTS.md pack/AGENTS.md skills/README.md docs/ai-first-saas-application-architecture.md
require_rg "Applications generated by this skills pack are \*\*secure AI-first SaaS applications by default\*\*" docs/ai-first-saas-application-architecture.md
require_rg "core-saas-foundation" skills/README.md

log "checking broad intake and generation skills route through core foundation"
require_rg "core-saas-foundation" \
  skills/ai-first-saas/SKILL.md \
  skills/akka-solution-decomposition/SKILL.md \
  skills/akka-prd-to-specs-backlog/SKILL.md \
  skills/app-description-bootstrap/SKILL.md \
  skills/app-generate-app/SKILL.md

log "checking packaged docs and seed app-description assets"
require_rg "docs/core-ai-first-saas-foundation.md" pack/manifest.yaml tools/build-pack.sh install.sh
require_rg "docs/core-saas-identity-tenancy-admin.md" pack/manifest.yaml tools/build-pack.sh install.sh
require_rg "docs/core-saas-owner-tenant-billing.md" pack/manifest.yaml tools/build-pack.sh install.sh
require_rg "docs/examples/ai-first-saas-seed-app-description/README.md" pack/manifest.yaml tools/build-pack.sh install.sh
require_rg "docs/examples/ai-first-saas-seed-app-description/app-description/00-system/app-manifest.md" pack/manifest.yaml tools/build-pack.sh install.sh

log "checking forbidden optional-security phrasing in top-level routing files"
forbid_rg "security.*optional|optional.*security|when security is in scope|only when security is in scope|JWT/internal security skills only when security is in scope|generic Akka app|ordinary Akka app|CRUD-first" \
  AGENTS.md \
  pack/AGENTS.md \
  skills/README.md \
  docs/ai-first-saas-application-architecture.md

log "checking shell syntax for pack scripts"
bash -n tools/build-pack.sh install.sh

log "verification passed"
